# Cors config
quarkus:
  http:
    cors:
      ~: true
      methods: GET,PUT,POST

# REST Client configuration property
bzh:
  jojal:
    web:
      client:
        CodingLoveClient/mp-rest/url: https://lesjoiesducode.fr/
        scope: javax.inject.Singleton

